### ISSUE TITLE
Request dataset

### ISSUE THREAD

**Issue by v3551G** [ploymel/estimateBP#1]
Can you provide me the dataset? the url can not be accessible. masterqkk@outlook.com.
Thank you very much.

**Comment by thamolwanpo** [comment]
Oh! I might have accidentally remove the dataset I used for this project, however you can use [UCI: Cuff-Less Blood Pressure Estimation Data Set](https://archive.ics.uci.edu/ml/datasets/Cuff-Less+Blood+Pressure+Estimation). It's a little bit different from the one I used, but it should be work just fine.

**Comment by imadMansour85** [comment]
Hey can you provide the dataset please ?
